name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.3, 8.2]
        laravel: [10.*, 11.*] # Add Laravel 11
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*  # Define Laravel 11 with the correct Testbench version
            testbench: 9.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Configure GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "git@github.com:"

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.laravel }}" == "10.*" ]]; then
            composer require "laravel/framework:${{ matrix.laravel }}" \
                            "orchestra/testbench:${{ matrix.testbench }}" \
                            "pestphp/pest-plugin-laravel:^2.0" \
                            "pestphp/pest-plugin-arch:^2.0" \
                            "nunomaduro/collision:^8.1.1" --dev --no-interaction --no-update
          else
            composer require "laravel/framework:${{ matrix.laravel }}" \
                            "orchestra/testbench:${{ matrix.testbench }}" \
                            "pestphp/pest-plugin-laravel:^3.0" \
                            "pestphp/pest-plugin-arch:^3.0" \
                            "nunomaduro/collision:^7.0" --dev --no-interaction --no-update
          fi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci
